Repository Team-uMigrate/umigrate, pull requests merged in 2020-09, with the labels that each got.

#41 Spelling error
  api/src/common/constants/choices.py
Labels: bug fix, ready to merge

#42 Navigation Bar ui improvements
  website/src/package-lock.json
  website/src/package.json
  website/src/src/components/Advertisements/AdToolbar/AdTopbar.jsx
  website/src/src/components/Advertisements/AdToolbar/index.jsx
  website/src/src/components/Advertisements/AdsPage.jsx
  website/src/src/components/Common/MenuBar/BackDrop.jsx
  website/src/src/components/Common/MenuBar/DrawerTogglerButton.jsx
  website/src/src/components/Common/MenuBar/MenuBar.css
  website/src/src/components/Common/MenuBar/MenuBar.jsx
  website/src/src/components/Common/MenuBar/MenuBarStyles.css
  website/src/src/components/Common/MenuBar/MenuBarView.jsx
  website/src/src/components/Common/MenuBar/SideBar.jsx
  website/src/src/components/Common/MenuBar/TopBar.css
  website/src/src/components/Common/MenuBar/index.jsx
  website/src/src/components/Common/NavigationBar/NavigationBarContainer.jsx
  website/src/src/components/Common/NavigationBar/NavigationBarStyles.css
  website/src/src/components/Common/NavigationBar/NavigationBarView.jsx
  website/src/src/components/Common/NavigationBar/index.jsx
  website/src/src/components/Community/CommunityPage.jsx
  website/src/src/components/Community/CommunityToolbar/CommunityTopbar.jsx
  website/src/src/components/Housing/HousingPage.jsx
  website/src/src/components/Housing/HousingToolbar/HousingTopbar.jsx
  website/src/src/components/Housing/HousingToolbar/index.jsx
  website/src/src/components/Messaging/MessagingPage.jsx
  website/src/src/components/UserSettings/Common/SettingsBar/SettingsTopbar.jsx
  website/src/src/components/UserSettings/SettingsPage.jsx
  website/src/src/components/UsersPage/UsersPage.jsx
Labels: enhancement, ready to merge

#43 Feature/reorganize folder structure
  website/src/package-lock.json
  website/src/package.json
  website/src/src/components/Advertisements/index.jsx
  website/src/src/components/Common/MenuBar/MenuBarView.jsx
  website/src/src/components/Common/NavigationBar/NavigationBarContainer.jsx
  website/src/src/components/Common/NavigationBar/NavigationBarView.jsx
  website/src/src/components/Community/CommunitySidebar/index.jsx
  website/src/src/components/Community/CommunityToolbar/index.jsx
  website/src/src/components/Community/Event/EventContainer.jsx
  website/src/src/components/Community/Event/EventView.jsx
  website/src/src/components/Community/Event/index.jsx
  website/src/src/components/Community/Post/PostView.jsx
  website/src/src/components/Housing/Housing/index.jsx
  website/src/src/components/Housing/HousingPage.jsx
  website/src/src/components/Housing/HousingSidebar/index.jsx
  website/src/src/components/Housing/HousingToolbar/index.jsx
  website/src/src/components/Housing/Listings/ListingContainer.jsx
  website/src/src/components/Housing/Listings/ListingStyles.css
  website/src/src/components/Housing/Listings/ListingView.jsx
  website/src/src/components/Housing/Listings/index.jsx
  website/src/src/components/Login/Login/LoginView.jsx
  website/src/src/components/Login/LoginPage.jsx
  website/src/src/components/Market/Ads/AdContainer.jsx
  website/src/src/components/Market/Ads/AdStyles.css
  website/src/src/components/Market/Ads/AdView.jsx
  website/src/src/components/Market/Ads/index.jsx
  website/src/src/components/Market/MarketPage.jsx
  website/src/src/components/Market/MarketSidebar/index.jsx
  website/src/src/components/Market/MarketToolbar/index.jsx
  website/src/src/components/Market/index.jsx
  website/src/src/components/Messaging/Messages/MessageContainer.jsx
  website/src/src/components/Messaging/Rooms/RoomContainer.jsx
  website/src/src/components/Messaging/Rooms/RoomView.jsx
  website/src/src/components/Register/CreateUser/CreateUserView.jsx
  website/src/src/components/UserSettings/Account/AccountContainer.jsx
  website/src/src/components/UserSettings/Profile/ProfileView.jsx
  website/src/src/components/UsersPage/UsersPage/UsersContainer.jsx
  website/src/src/components/UsersPage/UsersPage/UsersView.jsx
  website/src/src/contexts/AuthContext.jsx
  website/src/src/contexts/RoomContext.jsx
  website/src/src/routers/AuthRouter.jsx
Labels: enhancement, ready to merge

#61 Move from Session auth to token auth
  website/src/src/components/Common/NavigationBar/NavigationBarContainer.jsx
  website/src/src/components/Login/Login/LoginContainer.jsx
  website/src/src/components/Register/CreateUser/CreateUserContainer.jsx
  website/src/src/components/Register/Verification/VerificationContainer.jsx
  website/src/src/components/UserSettings/Profile/ProfileContainer.jsx
  website/src/src/constants/urls/apiUrls.jsx
  website/src/src/contexts/AuthContext.jsx
  website/src/src/routers/AuthRouter.jsx
  website/src/src/utils/api/resources/createResource.jsx
  website/src/src/utils/api/resources/destroyResource.jsx
  website/src/src/utils/api/resources/likeResource.jsx
  website/src/src/utils/api/resources/listResource.jsx
  website/src/src/utils/api/resources/retrieveResource.jsx
  website/src/src/utils/api/resources/updateResource.jsx
Labels: bug fix, ready to merge

#115 Feature/add navigation
  mobile/src/App.js
  mobile/src/package-lock.json
  mobile/src/package.json
  mobile/src/src/components/community/CommunityPage.jsx
  mobile/src/src/components/community/index.jsx
  mobile/src/src/components/housing/HousingPage.jsx
  mobile/src/src/components/housing/index.jsx
  mobile/src/src/components/login/LoginPage.jsx
  mobile/src/src/components/login/index.jsx
  mobile/src/src/components/market/MarketPage.jsx
  mobile/src/src/components/market/index.jsx
  mobile/src/src/components/menu/MenuPage.jsx
  mobile/src/src/components/menu/index.jsx
  mobile/src/src/components/messaging/MessagingPage.jsx
  mobile/src/src/components/messaging/index.jsx
  mobile/src/src/components/notifications/NotificationsPage.jsx
  mobile/src/src/components/notifications/index.jsx
  mobile/src/src/components/register/RegistrationPage.jsx
  mobile/src/src/components/register/index.jsx
  mobile/src/src/constants/apiEndpoints.jsx
  mobile/src/src/contexts/AuthContext.jsx
  mobile/src/src/navigators/AuthNavigator.jsx
  mobile/src/src/navigators/TabNavigator.jsx
  mobile/src/yarn.lock
Labels: do not merge

#119 Feature/create header bar
  mobile/src/App.js
  mobile/src/assets/favicon.png
  mobile/src/src/components/common/Header/Header.jsx
  mobile/src/src/components/common/Header/index.jsx
  mobile/src/src/components/community/CommunityPage.jsx
  mobile/src/src/components/housing/HousingPage.jsx
  mobile/src/src/components/login/LoginPage.jsx
  mobile/src/src/components/market/MarketPage.jsx
  mobile/src/src/components/menu/MenuPage.jsx
  mobile/src/src/components/messaging/MessagingPage.jsx
  mobile/src/src/components/notifications/NotificationsPage.jsx
  mobile/src/src/components/register/RegistrationPage.jsx
  mobile/src/src/contexts/NavContext.jsx
  mobile/src/src/navigators/AuthNavigator.jsx
  mobile/src/src/navigators/TabNavigator.jsx
Labels: ready to merge

#120 Feature/add create button
  mobile/src/package.json
  mobile/src/src/components/common/Header/Header.jsx
  mobile/src/src/components/community/CommunityPage.jsx
Labels: ready to merge

#123 moved localStorage to sessionStorage
  website/src/package-lock.json
  website/src/src/components/Common/NavigationBar/NavigationBarContainer.jsx
  website/src/src/components/Common/NavigationBar/NavigationBarView.jsx
  website/src/src/components/Login/Login/LoginContainer.jsx
  website/src/src/components/Messaging/Messages/MessageContainer.jsx
  website/src/src/components/Messaging/Rooms/RoomView.jsx
  website/src/src/components/Register/CreateUser/CreateUserContainer.jsx
  website/src/src/constants/misc/localStorageKeys.jsx
  website/src/src/constants/misc/sessionStorageKeys.jsx
  website/src/src/contexts/AuthContext.jsx
  website/src/src/utils/api/resources/updateResource.jsx
Labels: ready to merge

#130 Feature/rename housing to listing
  api/src/common/constants/choices.py
  api/src/common/utils/create_resources.py
  api/src/housing/admin.py
  api/src/housing/api_views.py
  api/src/housing/migrations/0002_auto_20200508_1732.py
  api/src/housing/serializers.py
  api/src/housing/urls.py
  api/src/listings/__init__.py
  api/src/listings/admin.py
  api/src/listings/api_views.py
  api/src/listings/apps.py
  api/src/listings/filters.py
  api/src/listings/migrations/0001_initial.py
  api/src/listings/migrations/__init__.py
  api/src/listings/models.py
  api/src/listings/serializers.py
  api/src/listings/tests.py
  api/src/listings/urls.py
  api/src/umigrate/settings.py
  api/src/umigrate/urls.py
Labels: ready to merge

#148 Feature/add error modal
  mobile/src/src/components/login/LoginPage.jsx
  mobile/src/src/components/register/RegistrationPage.jsx
Labels: ready to merge

#164 Refactored all models
  api/src/ads/filters.py
  api/src/ads/migrations/0003_auto_20200917_2232.py
  api/src/ads/models.py
  api/src/ads/tests.py
  api/src/common/constants/choices.py
  api/src/common/generics/generic_post_models.py
  api/src/common/generics/generic_post_tests.py
  api/src/common/utils/create_resources.py
  api/src/events/api_views.py
  api/src/events/migrations/0003_auto_20200917_2232.py
  api/src/events/models.py
  api/src/events/tests.py
  api/src/jobs/migrations/0004_auto_20200917_2232.py
  api/src/jobs/models.py
  api/src/jobs/tests.py
  api/src/listings/filters.py
  api/src/listings/migrations/0002_auto_20200917_2232.py
  api/src/listings/models.py
  api/src/listings/tests.py
  api/src/messaging/migrations/0003_auto_20200917_2232.py
  api/src/messaging/models.py
  api/src/polls/migrations/0003_auto_20200917_2232.py
  api/src/polls/models.py
  api/src/polls/tests.py
  api/src/posts/migrations/0003_auto_20200917_2232.py
  api/src/posts/tests.py
  api/src/users/api_views.py
  api/src/users/migrations/0003_auto_20200917_2232.py
  api/src/users/models.py
  api/src/users/serializers.py
  api/src/users/tests.py
Labels: ready to merge

#166 Feature/improve liking resources
  api/src/ads/api_views.py
  api/src/ads/migrations/0004_auto_20200920_0055.py
  api/src/ads/serializers.py
  api/src/ads/urls.py
  api/src/common/generics/generic_post_api_views.py
  api/src/common/generics/generic_post_models.py
  api/src/common/generics/generic_post_tests.py
  api/src/common/generics/generic_serializers.py
  api/src/events/api_views.py
  api/src/events/migrations/0004_auto_20200920_0055.py
  api/src/events/serializers.py
  api/src/events/tests.py
  api/src/events/urls.py
  api/src/jobs/tests.py
  api/src/listings/api_views.py
  api/src/listings/migrations/0003_auto_20200920_0055.py
  api/src/listings/serializers.py
  api/src/listings/urls.py
  api/src/messaging/tests.py
  api/src/polls/api_views.py
  api/src/polls/migrations/0004_auto_20200920_0055.py
  api/src/polls/serializers.py
  api/src/polls/urls.py
  api/src/posts/api_views.py
  api/src/posts/migrations/0004_auto_20200920_0055.py
  api/src/posts/serializers.py
  api/src/posts/urls.py
  api/src/users/api_views.py
  api/src/users/models.py
  api/src/users/serializers.py
  api/src/users/tests.py
  api/src/users/urls.py
Labels: do not merge

#171 Feature/add class schema decorators
  api/src/ads/api_views.py
  api/src/events/api_views.py
  api/src/jobs/api_views.py
  api/src/listings/api_views.py
  api/src/messaging/api_views.py
  api/src/polls/api_views.py
  api/src/posts/api_views.py
  api/src/users/api_views.py
Labels: ready to merge

#198 Feature/basic user serializer
  api/src/ads/serializers.py
  api/src/common/generics/generic_post_serializers.py
  api/src/common/generics/generic_post_tests.py
  api/src/common/generics/generic_serializers.py
  api/src/events/serializers.py
  api/src/jobs/serializers.py
  api/src/listings/serializers.py
  api/src/messaging/serializers.py
  api/src/messaging/tests.py
  api/src/polls/serializers.py
  api/src/posts/serializers.py
  api/src/users/serializers.py
Labels: ready to merge

#177 Feature/add location field to resources
  api/src/ads/filters.py
  api/src/ads/migrations/0005_ad_postal_code.py
  api/src/ads/models.py
  api/src/ads/tests.py
  api/src/common/utils/create_resources.py
  api/src/events/api_views.py
  api/src/events/migrations/0005_event_location.py
  api/src/events/models.py
  api/src/events/tests.py
  api/src/listings/filters.py
  api/src/listings/migrations/0004_listing_location.py
  api/src/listings/models.py
  api/src/listings/tests.py
Labels: ready to merge

#210 Modified ads to use query string endpoint
  api/src/ads/api_views.py
  api/src/ads/urls.py
  api/src/common/generics/generic_post_api_views.py
  api/src/common/generics/generic_post_serializers.py
  api/src/common/generics/generic_post_tests.py
  api/src/events/api_views.py
  api/src/events/urls.py
  api/src/jobs/api_views.py
  api/src/jobs/tests.py
  api/src/jobs/urls.py
  api/src/listings/api_views.py
  api/src/listings/urls.py
  api/src/polls/api_views.py
  api/src/polls/tests.py
  api/src/polls/urls.py
  api/src/posts/api_views.py
  api/src/posts/urls.py
  api/src/requirements.txt
Labels: ready to merge

#212 ISSUE#64 - Login registration UI modified for mobile
  mobile/src/App.jsx
  mobile/src/assets/templatedLogin.png
  mobile/src/assets/templatedRegister.png
  mobile/src/package-lock.json
  mobile/src/package.json
  mobile/src/src/components/Login/LoginPage.jsx
  mobile/src/src/components/Register/RegistrationPage.jsx
  mobile/src/yarn.lock
Labels: ready to merge

#178 added sentry to required external libraries + settings.py
  api/src/common/constants/choices.py
  api/src/requirements.txt
  api/src/umigrate/settings.py
  api/src/umigrate/urls.py
Labels: ready to merge

#176 re-enable npm test in pipelines
  mobile/.gitignore
  website/.gitignore
  website/deployment/azure-pipelines.yml
  website/src/package-lock.json
  website/src/package.json
  website/src/src/tests/App.test.js
Labels: ready to merge

#208 Render Listings to the Housing Page
  mobile/src/src/components/Housing/HousingPage.jsx
  mobile/src/src/components/Housing/Listings/ListingView.jsx
  mobile/src/src/components/Housing/Listings/ListingsContainer.jsx
  mobile/src/src/components/common/ProfilePhoto.jsx
Labels: ready to merge
