Repository Team-uMigrate/umigrate, pull requests merged in 2020-07, with the labels that each got.

#25 Added min/max filters for date/price on Housing and Ad models
  api/src/ads/api_views.py
  api/src/ads/filters.py
  api/src/housing/api_views.py
  api/src/housing/filters.py
Labels: enhancement, ready to merge

#26 Fixed CSRF bug when running locally
  api/src/common/utils/local_authentication.py
  api/src/umigrate/settings.py
Labels: bug fix, ready to merge

#32 Feature/revise website registration
  api/src/ads/urls.py
  api/src/events/urls.py
  api/src/housing/urls.py
  api/src/messaging/urls.py
  api/src/polls/urls.py
  api/src/posts/urls.py
  api/src/umigrate/settings.py
  api/src/umigrate/urls.py
  api/src/users/urls.py
  website/src/src/components/App.jsx
  website/src/src/components/Common/MenuBar/MenuBar.jsx
  website/src/src/components/Community/Post/PostContainer.jsx
  website/src/src/components/Login/Login/LoginContainer.jsx
  website/src/src/components/Login/Login/LoginView.jsx
  website/src/src/components/Login/LoginPage.jsx
  website/src/src/components/Messaging/Messages/MessageContainer.jsx
  website/src/src/components/Messaging/Rooms/RoomContainer.jsx
  website/src/src/components/Messaging/Rooms/RoomView.jsx
  website/src/src/components/Register/CreateUser/CreateUser.jsx
  website/src/src/components/Register/CreateUser/CreateUserContainer.jsx
  website/src/src/components/Register/CreateUser/CreateUserStyles.css
  website/src/src/components/Register/CreateUser/CreateUserView.jsx
  website/src/src/components/Register/CreateUser/index.jsx
  website/src/src/components/Register/RegistrationPage.jsx
  website/src/src/components/Register/Verification/Verification.jsx
  website/src/src/components/Register/Verification/VerificationContainer.jsx
  website/src/src/components/Register/Verification/VerificationStyles.css
  website/src/src/components/Register/Verification/VerificationView.jsx
  website/src/src/components/Register/Verification/index.jsx
  website/src/src/components/UserSettings/Account/AccountContainer.jsx
  website/src/src/components/UserSettings/Profile/ProfileContainer.jsx
  website/src/src/constants/misc/localStorageKeys.jsx
  website/src/src/constants/urls/apiUrls.jsx
  website/src/src/contexts/AuthContext.jsx
  website/src/src/index.jsx
  website/src/src/routers/AuthRouter.jsx
  website/src/src/setupTests.jsx
  website/src/src/utils/api/resources/createResource.jsx
  website/src/src/utils/api/resources/destroyResource.jsx
  website/src/src/utils/api/resources/likeResource.jsx
  website/src/src/utils/api/resources/listResource.jsx
  website/src/src/utils/api/resources/retrieveResource.jsx
  website/src/src/utils/api/resources/updateResource.jsx
Labels: bug fix, enhancement, ready to merge
