Repository Team-uMigrate/umigrate, pull requests merged in 2020-10, with the labels that each got.

#214 feature/RenderAdsPage : Implements Rending of Ads Page
  mobile/src/src/components/Market/Ads/AdView.jsx
  mobile/src/src/components/Market/Ads/AdsContainer.jsx
  mobile/src/src/components/Market/MarketPage.jsx
Labels: ready to merge

#228 Modified Listings and Ads containers to match feed container
  mobile/src/src/components/Housing/Listings/ListingsContainer.jsx
  mobile/src/src/components/Market/Ads/AdsContainer.jsx
Labels: ready to merge

#226 Feature/community page
  mobile/src/src/components/Community/CommunityPage.jsx
  mobile/src/src/components/Community/Feed/EventView.jsx
  mobile/src/src/components/Community/Feed/FeedContainer.jsx
  mobile/src/src/components/Community/Feed/PostView.jsx
  mobile/src/src/components/Housing/Listings/ListingView.jsx
Labels: ready to merge

#231 add DB Backup/Restore Scripts
  infrastructure/src/crontab/umigratecron
  infrastructure/src/scripts/DBBackup.sh
  infrastructure/src/scripts/DBRestore.sh
  infrastructure/src/scripts/Virtualenv.sh
Labels: ready to merge

#243 Feature/background photo on user
  api/src/common/generics/generic_models.py
  api/src/jobs/migrations/0005_auto_20201008_2134.py
  api/src/jobs/migrations/0006_auto_20201008_2142.py
  api/src/jobs/models.py
  api/src/jobs/tests.py
  api/src/messaging/migrations/0004_auto_20201008_2134.py
  api/src/messaging/migrations/0005_auto_20201008_2142.py
  api/src/messaging/models.py
  api/src/messaging/tests.py
  api/src/users/migrations/0004_auto_20201006_2026.py
  api/src/users/migrations/0005_auto_20201006_2055.py
  api/src/users/models.py
  api/src/users/serializers.py
  api/src/users/tests.py
Labels: ready to merge

#144 Creating framework for Selenium System tests
  infrastructure/deployment/azure-pipelines.yml
  infrastructure/tests/SystemTests/SystemTests.csproj
  infrastructure/tests/SystemTests/SystemTests.sln
  infrastructure/tests/SystemTests/UnitTest1.cs
Labels: Cloud-Ops: Testing, medium, ready to merge

#247 Added liked-user endpoint
  api/src/ads/api_views.py
  api/src/common/generics/generic_post_api_views.py
  api/src/events/api_views.py
  api/src/listings/api_views.py
  api/src/polls/api_views.py
  api/src/posts/api_views.py
Labels: ready to merge

#250 Fix Status Bar height
  mobile/src/package-lock.json
  mobile/src/package.json
  mobile/src/src/components/common/Header/Header.jsx
Labels: ready to merge

#252 Feature/most liked comment postings
  api/src/common/generics/generic_post_serializers.py
  api/src/common/generics/generic_post_tests.py
Labels: ready to merge

#248 #202 - developed menu page and made buttons work
  mobile/src/src/components/Menu/HousingListingsPage.jsx
  mobile/src/src/components/Menu/MenuLogout.jsx
  mobile/src/src/components/Menu/MenuPage.jsx
  mobile/src/src/components/Menu/ProfilePage.jsx
  mobile/src/src/components/Menu/SavedPostsPage.jsx
  mobile/src/src/components/Menu/SettingsPage.jsx
  mobile/src/src/navigators/MenuNavigator.jsx
  mobile/src/src/navigators/TabNavigator.jsx
Labels: ready to merge

#255 Create comment bar
  mobile/src/src/components/Housing/Listings/ListingView.jsx
  mobile/src/src/components/Housing/Listings/ListingsContainer.jsx
  mobile/src/src/components/common/CommentBar/CommentBar.jsx
  mobile/src/src/components/common/CommentBar/CommentBarButtons.jsx
  mobile/src/src/utils/endpoints.js
Labels: ready to merge

#261 Fix indentation in a few files
  mobile/src/src/components/Housing/Listings/ListingView.jsx
  mobile/src/src/components/Housing/Listings/ListingsContainer.jsx
  mobile/src/src/components/common/CommentBar/CommentBar.jsx
  mobile/src/src/components/common/CommentBar/CommentBarButtons.jsx
Labels: ready to merge

#262 Feature/most liked comment postings
  api/src/common/generics/generic_models.py
  api/src/common/generics/generic_post_tests.py
  api/src/messaging/tests.py
  api/src/posts/serializers.py
Labels: ready to merge

#263 Added saved postings endpoint for GET and POST
  api/src/ads/migrations/0006_auto_20201015_2250.py
  api/src/ads/migrations/0007_adcomment_saved_posts.py
  api/src/ads/migrations/0008_auto_20201015_2324.py
  api/src/common/generics/generic_post_api_views.py
  api/src/common/generics/generic_post_models.py
  api/src/common/generics/generic_post_serializers.py
  api/src/common/generics/generic_post_tests.py
  api/src/events/migrations/0006_auto_20201015_2250.py
  api/src/events/migrations/0007_eventcomment_saved_posts.py
  api/src/events/migrations/0008_auto_20201015_2324.py
  api/src/listings/migrations/0005_auto_20201015_2250.py
  api/src/listings/migrations/0006_listingcomment_saved_posts.py
  api/src/listings/migrations/0007_auto_20201015_2324.py
  api/src/polls/migrations/0005_auto_20201015_2250.py
  api/src/polls/migrations/0006_pollcomment_saved_posts.py
  api/src/polls/migrations/0007_auto_20201015_2324.py
  api/src/posts/migrations/0005_auto_20201015_2250.py
  api/src/posts/migrations/0006_postcomment_saved_posts.py
  api/src/posts/migrations/0007_auto_20201015_2324.py
  api/src/users/api_views.py
  api/src/users/urls.py
Labels: ready to merge

#266 Feature/events serializer
  api/src/events/serializers.py
Labels: ready to merge

#264 Improve API tests with Factory boy
  api/src/ads/factories.py
  api/src/ads/migrations/0006_auto_20201011_2130.py
  api/src/ads/migrations/0007_auto_20201012_1907.py
  api/src/ads/migrations/0009_merge_20201017_1300.py
  api/src/ads/models.py
  api/src/ads/serializers.py
  api/src/ads/tests.py
  api/src/common/abstract_tests.py
  api/src/common/constants/choices.py
  api/src/common/generics/generic_factories.py
  api/src/events/factories.py
  api/src/events/migrations/0006_auto_20201011_2130.py
  api/src/events/migrations/0009_merge_20201017_1300.py
  api/src/events/models.py
  api/src/events/serializers.py
  api/src/events/tests.py
  api/src/jobs/factories.py
  api/src/jobs/migrations/0007_auto_20201011_2130.py
  api/src/jobs/models.py
  api/src/listings/factories.py
  api/src/listings/migrations/0005_auto_20201011_2130.py
  api/src/listings/migrations/0006_auto_20201012_1907.py
  api/src/listings/migrations/0008_merge_20201017_1300.py
  api/src/listings/models.py
  api/src/listings/serializers.py
  api/src/listings/tests.py
  api/src/messaging/factories.py
  api/src/messaging/migrations/0006_auto_20201011_2130.py
  api/src/messaging/migrations/0007_auto_20201012_2134.py
  api/src/messaging/models.py
  api/src/polls/factories.py
  api/src/polls/migrations/0005_auto_20201011_2130.py
  api/src/polls/migrations/0008_merge_20201017_1300.py
  api/src/polls/serializers.py
  api/src/polls/tests.py
  api/src/posts/factories.py
  api/src/posts/migrations/0005_auto_20201011_2130.py
  api/src/posts/migrations/0008_merge_20201017_1300.py
  api/src/posts/serializers.py
  api/src/posts/tests.py
  api/src/requirements.txt
  api/src/users/factories.py
  api/src/users/migrations/0006_auto_20201011_2130.py
  api/src/users/models.py
Labels: do not merge

#254 Add create button and page
  mobile/src/src/components/Create/CreatePage.jsx
  mobile/src/src/components/Create/index.jsx
  mobile/src/src/navigators/TabNavigator.jsx
Labels: Mobile: Maintenance, hacktoberfest-accepted, ready to merge

#270 Added Validation for start and end dates
  api/src/events/factories.py
  api/src/events/models.py
Labels: ready to merge

#267 feature/EventButtonsFunctionality: Implements Functionality
  mobile/src/src/components/Community/Feed/EventView.jsx
  mobile/src/src/components/Community/Feed/FeedContainer.jsx
  mobile/src/src/utils/endpoints.js
Labels: Mobile: Maintenance, hacktoberfest-accepted, ready to merge

#249 Sample react native tests
  mobile/src/babel.config.js
  mobile/src/package-lock.json
  mobile/src/package.json
  mobile/src/src/components/Community/Feed/FeedContainer.test.jsx
  mobile/src/src/components/Community/Feed/PostView.jsx
  mobile/src/src/components/Community/Feed/PostView.test.jsx
  mobile/src/src/setupTests.js
  mobile/src/src/utils/mockData.js
  mobile/src/src/utils/mockEndpoints.js
Labels: ready to merge

#288 feature/DevelopHeader : Implements New Header Design
  mobile/src/src/components/Notifications/NotificationsPage.jsx
  mobile/src/src/components/common/Header/Header.jsx
  mobile/src/src/navigators/AuthNavigator.jsx
Labels: Mobile: Maintenance, hacktoberfest-accepted, ready to merge

#291 Update comment endpoints
  mobile/src/src/utils/endpoints.js
Labels: ready to merge
