Repository Team-uMigrate/umigrate, pull requests merged in 2020-08, with the labels that each got.

#33 Feature/import messaging
  api/src/messaging/consumers.py
  api/src/messaging/routing.py
  api/src/messaging/templates/index.html
  api/src/messaging/templates/room.html
  api/src/messaging/urls.py
  api/src/messaging/views.py
  api/src/umigrate/routing.py
  website/src/src/components/Messaging/Messages/MessageContainer.jsx
  website/src/src/components/Messaging/Messages/MessageView.jsx
  website/src/src/components/Messaging/MessagingPage.jsx
  website/src/src/components/Messaging/Rooms/RoomContainer.jsx
  website/src/src/components/Messaging/Rooms/RoomView.jsx
  website/src/src/contexts/RoomContext.jsx
  website/src/src/routers/AuthRouter.jsx
Labels: enhancement, ready to merge

#34 Feature/revise api utils
  website/src/src/components/UserSettings/Account/AccountContainer.jsx
  website/src/src/components/UserSettings/Profile/ProfileContainer.jsx
Labels: bug fix, ready to merge

#36 Changed daphne service file to template file
  infrastructure/src/services/daphne@.service
Labels: ready to merge

#39 Feature/create mobile
  mobile/.gitignore
  mobile/README.md
  mobile/src/.expo-shared/assets.json
  mobile/src/App.js
  mobile/src/app.json
  mobile/src/assets/favicon.png
  mobile/src/assets/icon.png
  mobile/src/assets/splash.png
  mobile/src/babel.config.js
  mobile/src/package.json
  mobile/src/yarn.lock
Labels: ready to merge
