Repository Team-uMigrate/umigrate, pull requests merged in 2021-06, with the labels that each got.

#431 Feature/408 modularize createcommunityscreen
  app/src/src/components/common/CommunitySelectModal.jsx
  app/src/src/components/common/FormatDate/toYearMonthDayInNumbers.jsx
  app/src/src/components/common/FormatDate/toYearMonthDayTimeInNumbers.jsx
  app/src/src/components/modals/PickADayTimeModal.jsx
  app/src/src/screens/createItem/CreateCommunityScreen.jsx
Labels: ready to merge

#449 API: References to shared items in message objects #241
  api/src/messaging/consumers.py
  api/src/messaging/migrations/0003_auto_20210531_0258 2.py
  api/src/messaging/migrations/0003_auto_20210531_0258.py
  api/src/messaging/migrations/0004_alter_message_content_type 2.py
  api/src/messaging/migrations/0004_alter_message_content_type.py
  api/src/messaging/migrations/0005_merge_20210605_0443.py
  api/src/messaging/models.py
  api/src/messaging/templates/room.html
Labels: ready to merge

#432 Feature/Added room membership join date
  api/src/messaging/api_views.py
  api/src/messaging/migrations/0001_initial.py
  api/src/messaging/migrations/0002_auto_20201128_2031.py
  api/src/messaging/migrations/0003_auto_20210531_0258 2.py
  api/src/messaging/migrations/0003_auto_20210531_0258.py
  api/src/messaging/migrations/0004_alter_message_content_type 2.py
  api/src/messaging/migrations/0004_alter_message_content_type.py
  api/src/messaging/migrations/0005_merge_20210605_0443.py
  api/src/messaging/models.py
  api/src/messaging/serializers.py
  api/src/messaging/urls.py
Labels: ready to merge

#417 Feature/Creates Searchbar Component
  app/src/src/components/common/FeedContainerHeader.jsx
  app/src/src/components/containers/FeedContainer.jsx
  app/src/src/components/containers/SearchResults.jsx
  app/src/src/components/views/SearchPageView.jsx
  app/src/src/screens/tabs/CommunityScreen.jsx
  app/src/src/screens/tabs/HousingScreen.jsx
  app/src/src/screens/tabs/MarketScreen.jsx
Labels: ready to merge

#456 Bug fix: Fix CommentsScreen error
  app/src/src/screens/comments/CommentsScreen.jsx
Labels: bug fix, ready to merge

#457 Load feed screens asynchronously
  app/src/package.json
  app/src/src/navigators/TabNavigator.jsx
Labels: dependencies, ready to merge

#445 Feature/notification triggers2
  api/src/common/abstract_api_views.py
  api/src/common/notification_helpers.py
  api/src/messaging/consumers.py
  api/src/users/api_views.py
Labels: ready to merge

#450 Feature/tighten-messaging-consumer
  api/src/messaging/consumers.py
  api/src/messaging/receive.py
  api/src/messaging/views.py
Labels: ready to merge

#458 added code to embed django-rq
  api/src/requirements.txt
  api/src/umigrate/settings.py
  api/src/umigrate/urls.py
Labels: ready to merge

#465 Refactor feed
  app/src/package-lock.json
  app/src/src/components/common/FeedHeader.jsx
  app/src/src/components/containers/FeedContainer.jsx
  app/src/src/components/containers/FeedContainer.test.jsx
  app/src/src/components/containers/SearchResults.jsx
  app/src/src/components/views/SearchPageView.jsx
  app/src/src/screens/comments/CommentsScreen.jsx
  app/src/src/screens/tabs/CommunityScreen.jsx
  app/src/src/screens/tabs/HousingScreen.jsx
  app/src/src/screens/tabs/MarketScreen.jsx
  app/src/src/utils/choices.js
Labels: ready to merge

#467 Updated Attending and Interested buttons
  app/src/src/components/views/EventView.jsx
Labels: ready to merge

#478 Refactor the feed container
  app/src/src/components/common/FeedHeader.jsx
  app/src/src/components/containers/FeedContainer.jsx
  app/src/src/components/containers/SearchContainer.jsx
  app/src/src/components/views/SearchView.jsx
  app/src/src/navigators/AuthNavigator.jsx
  app/src/src/screens/comments/CommentsScreen.jsx
  app/src/src/screens/search/SearchScreen.jsx
  app/src/src/screens/tabs/CommunityScreen.jsx
  app/src/src/screens/tabs/HousingScreen.jsx
  app/src/src/screens/tabs/MarketScreen.jsx
  app/src/src/utils/endpoints.js
  app/src/src/utils/fetchDataHelpers.js
  app/src/src/utils/routes.js
Labels: ready to merge

#480 Keep items on screen when refreshing
  app/src/src/components/containers/FeedContainer.jsx
  app/src/src/utils/fetchDataHelpers.js
Labels: ready to merge

#481 Documentation/add jsdoc comments
  app/src/src/components/containers/FeedContainer.jsx
  app/src/src/contexts/AuthContext.jsx
  app/src/src/contexts/CreateItemContext.jsx
  app/src/src/contexts/ErrorContext.jsx
  app/src/src/contexts/TabNavContext.jsx
  app/src/src/navigators/AuthNavigator.jsx
  app/src/src/navigators/AuthNavigator.test.jsx
  app/src/src/navigators/MenuNavigator.jsx
  app/src/src/navigators/TabNavigator.jsx
  app/src/src/screens/authentication/LoadingScreen.jsx
  app/src/src/screens/authentication/LoadingScreen.test.jsx
  app/src/src/screens/authentication/LoginScreen.jsx
  app/src/src/screens/authentication/LoginScreen.test.jsx
  app/src/src/screens/authentication/PasswordResetScreen.jsx
  app/src/src/screens/authentication/PasswordResetScreen.test.jsx
  app/src/src/screens/authentication/RegistrationScreen.jsx
  app/src/src/screens/authentication/RegistrationScreen.test.jsx
  app/src/src/screens/comments/CommentsScreen.jsx
  app/src/src/utils/endpoints.js
  app/src/src/utils/fetchDataHelpers.js
  app/src/src/utils/routes.js
  app/src/src/utils/storageAccess.js
Labels: ready to merge

#482 Feature/refactor comments view
  app/src/App.jsx
  app/src/src/components/containers/FeedContainer.jsx
  app/src/src/components/containers/ReplyContainer.jsx
  app/src/src/components/views/CommentView.jsx
  app/src/src/components/views/ReplyView.jsx
  app/src/src/screens/authentication/LoadingScreen.jsx
  app/src/src/screens/comments/CommentsScreen.jsx
  app/src/src/utils/endpoints.js
  app/src/src/utils/fetchDataHelpers.js
Labels: ready to merge

#484 add comments to pre-delete function
  api/src/messaging/models.py
Labels: ready to merge

#489 Feature: Users can only see messages that are sent after they joined
  api/src/messaging/api_views.py
Labels: ready to merge

#491 Create and use AbstractCreator serializer
  api/src/comments/serializers.py
  api/src/common/abstract_serializers.py
Labels: ready to merge
